<?xml version="1.0"?>
<package format="3">
  <name>project_seeder</name>
  <version>0.0.1</version>
  <description>Tree waypoint goals, odom bridge, and colour detection nodes</description>
  <maintainer email="you@example.com">You</maintainer>
  <license>Apache-2.0</license>

  <!-- runtime deps -->
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>image_transport</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <!-- IMPORTANT: tell colcon this is a Python package -->
    <build_type>ament_python</build_type>
  </export>
</package>
